config/routes.rb
Rails.application.routes.draw do
  resources :cos

end

app/models/co.rb
class Co < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cos_controller.rb
class CosController < ApplicationController
  before_action :set_co, only: [:show, :edit, :update, :destroy]

  # GET /cos
  # GET /cos.json
  def index
    @cos = Co.all
  end

  # GET /cos/1
  # GET /cos/1.json
  def show
  end

  # GET /cos/new
  def new
    @co = Co.new
  end

  # GET /cos/1/edit
  def edit
  end

  # POST /cos
  # POST /cos.json
  def create
    @co = Co.new(co_params)

    respond_to do |format|
      if @co.save
        format.html { redirect_to @co, notice: 'Co was successfully created.' }
        format.json { render :show, status: :created, location: @co }
      else
        format.html { render :new }
        format.json { render json: @co.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cos/1
  # PATCH/PUT /cos/1.json
  def update
    respond_to do |format|
      if @co.update(co_params)
        format.html { redirect_to @co, notice: 'Co was successfully updated.' }
        format.json { render :show, status: :ok, location: @co }
      else
        format.html { render :edit }
        format.json { render json: @co.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cos/1
  # DELETE /cos/1.json
  def destroy
    @co.destroy
    respond_to do |format|
      format.html { redirect_to cos_url, notice: 'Co was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_co
      @co = Co.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def co_params
      params.require(:co).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cos_helper.rb
module CosHelper
end

app/views/cos/_form.html.erb
<%= form_for(@co) do |f| %>
  <% if @co.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@co.errors.count, "error") %> prohibited this co from being saved:</h2>

      <ul>
      <% @co.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cos/edit.html.erb
<h1>Editing Co</h1>

<%= render 'form' %>

<%= link_to 'Show', @co %> |
<%= link_to 'Back', cos_path %>

app/views/cos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cos.each do |co| %>
      <tr>
        <td><%= co.name %></td>
        <td><%= co.description %></td>
        <td><%= link_to 'Show', co %></td>
        <td><%= link_to 'Edit', edit_co_path(co) %></td>
        <td><%= link_to 'Destroy', co, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Co', new_co_path %>

app/views/cos/new.html.erb
<h1>New Co</h1>

<%= render 'form' %>

<%= link_to 'Back', cos_path %>

app/views/cos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @co.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @co.description %>
</p>

<%= link_to 'Edit', edit_co_path(@co) %> |
<%= link_to 'Back', cos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testowy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>